version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    
    volumes:
      - ./apps/backend/prisma:/app/apps/backend/prisma
      - ./apps/backend/prisma/dev.db:/app/apps/backend/prisma/dev.db
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: file:./dev.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:80"
volumes:
  node_modules: {}